### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by BaohaoLiao** [SamratThapa120/gradio-ASL-fingerspelling-recognition#1]
Hi,

when I install the packages in the requirement, it raises an error of 

ERROR: Could not find a version that satisfies the requirement tflite-runtime==2.13.0 (from versions: none)
ERROR: No matching distribution found for tflite-runtime==2.13.0

**Comment by SamratThapa120** [comment]
Are you using the [python:3.8.17](https://hub.docker.com/layers/library/python/3.8.17/images/sha256-0e415e6e4f2e754146e2a279a3d14729e898b6dc936d9d75897f168e564170e8?context=explore) docker image?

**Comment by BaohaoLiao** [comment]
No, I don't use docker

**Comment by BaohaoLiao** [comment]
I didn't use docker.

I retry to use docker as your instruction, and make some necessary changes to requirement.txt as:
```
 mediapipe==0.10.3 # change from 0.10.0 to 0.10.3
 gradio # add
```
However, it raises an error of 
```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.8/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/usr/local/lib/python3.8/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/usr/local/lib/python3.8/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/usr/local/lib/python3.8/site-packages/mediapipe/python/solutions/drawing_utils.py", line 20, in <module>
    import cv2
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
```
